### ISSUE TITLE
Rename log files to share the output filestem and evaluate successful runs. 

### ISSUE THREAD

**Issue by Gerenjie** [dirac-institute/sorcha#1003]
**Describe the feature you'd like to see in Sorcha**
Currently, Sorcha log files have long names starting with a date, which are not easily identified to their output files. It would be helpful for the log files to share a filestem with their output files, which would allow for easy identification and diagnosis of runtime issues. 

It would also be helpful to have a more explicit/obvious report of the job's failure/success -- I forget what the proposed solution was in the last meeting, but at the moment I'm seeing 'COMPLETED' as the result of slurm jobs even when Sorcha fails, which has tripped me up before (though it was my failure to not investigate the log files properly).

**Comment by mschwamb** [comment]
Have a script that looks through the current directory or directory provided and checks that the last line of the log file is that it succeeded and print out when there is a failure and when it was fine

**Comment by astronomerritt** [comment]
Do we still want to keep the datetime in the log filename?

**Comment by mschwamb** [comment]
Yes, I think so plus process ID
