### ISSUE TITLE
Need to update spice kernels because of a JPL update (so CI unit tests start working again)

### ISSUE THREAD

**Issue by mschwamb** [dirac-institute/sorcha#1008]
https://naif.jpl.nasa.gov/pub/naif/generic_kernels/pck/earth_720101_230601.bpc is now https://naif.jpl.nasa.gov/pub/naif/generic_kernels/pck/earth_620120_240827.bpc (EDITED per Pedro's comment)

https://naif.jpl.nasa.gov/pub/naif/generic_kernels/pck/earth_200101_990825_predict.bpc is now https://naif.jpl.nasa.gov/pub/naif/generic_kernels/pck/earth_200101_990827_predict.bpc

@matthewholman  can you give a double check that I've picked the correct files here to switch to

**Comment by bernardinelli** [comment]
I think the first one (`720101_230601`) should be https://naif.jpl.nasa.gov/pub/naif/generic_kernels/pck/earth_620120_240827.bpc
Looking at the SPICE documentation, I see that `000101_241120_240827` file is the weekly update, while `72...` and `62....` are the "historical" kernels

**Comment by mschwamb** [comment]
And add scipy as an explicit requirement
