### ISSUE TITLE
sorcha-run without any parameters does not give intuitive suggestions

### ISSUE THREAD

**Issue by fedorets** [dirac-institute/sorcha#1019]
When running 'sorcha-run' the command-line suggestions are not intuitive.

It was mutually agreed that in this case, the output of 'sorcha-run -h' is desired. 

#978 is a related issue.

**Comment by mschwamb** [comment]
That's not quite what was agreed for in the call. We agreed that we can add a bit more detail on the usage line and an error message that reminds the user to use sorcha-run --help if they want a full refresher

**Comment by mjuric** [comment]
Hmm, what's the error message it outputs w/o the #1061 patch?

argparse should give the usual "short" summary of the command line options by default.

**Comment by mschwamb** [comment]
usage: sorcha-run [-h] -c C -o O -ob OB -p P -pd PD [-er ER] [-ew EW] [-ar AR]
                  [-cp CP] [-f] [-s S] [-t T] [-v] [-st ST]
sorcha-run: error: the following arguments are required: -c/--config, -o/--outfile, -ob/--orbit, -p/--params, -pd/--pointing_database
Error: Command 'sorcha-run' failed with exit code 2.

**Comment by mschwamb** [comment]
The beta tester thought it was not intuitive to know how to get help to know what all those things were

**Comment by mschwamb** [comment]
So I'm adding this only if you provide no command line arguments to sorcha run

`

Error: No command line arguments provided!!! 
Use the -h flag to see descriptions of the required and optional arguments needed to run Sorcha 

`

**Comment by mjuric** [comment]
I'll comment on the ticket, I'd propose one small tweak.
