### ISSUE TITLE
Repeatedly-crashing orbit

### ISSUE THREAD

**Issue by Gerenjie** [dirac-institute/sorcha#1049]
This (potentially-impacting) orbit causes Sorcha to hang:
`K10LE6Q,0.989417733988322,0.014048500388366,0.208955990447,310.2498245079728,161.4939297845983,55207.6498055619,55355.067039791,COM`

sorcha 0.9.3.dev0+g86724e7.d20241027
pandas 2.2.3
assist 1.1.9
rebound 4.4.1
sbpy 0.3.0

**Comment by mschwamb** [comment]
Very close encounters probably need full integration rather than integrate and interpolate.
