### ISSUE TITLE
Some functions aren't used in the code

### ISSUE THREAD

**Issue by astronomerritt** [dirac-institute/sorcha#1051]
These functions:

https://github.com/dirac-institute/sorcha/blob/e385ee0a8ee504ca1585afa7369365f664bd5e38/src/sorcha/modules/PPJoinEphemeridesAndParameters.py#L1-L24

https://github.com/dirac-institute/sorcha/blob/e385ee0a8ee504ca1585afa7369365f664bd5e38/src/sorcha/modules/PPJoinEphemeridesAndOrbits.py#L5-L30

They're only used in one place: the unit test for `PPMatchPointingToObservations()`. 

They are one-line functions which perform simple Pandas joins. I propose we remove these files/functions and their unit tests, and replace them in `test_PPMatchPointingToObservations()` with the Pandas join.

**Comment by mschwamb** [comment]
nice catch
