### ISSUE TITLE
PPReadPointingDatabase shouldn't except all errors

### ISSUE THREAD

**Issue by astronomerritt** [dirac-institute/sorcha#1058]
We have this in `PPReadPointingDatabase()`:

https://github.com/dirac-institute/sorcha/blob/7bcb8b6fa320436d79d2c8b97f7928185c37baf8/src/sorcha/modules/PPReadPointingDatabase.py#L33-L41

`except Exception` is bad practice. That except clause is triggering no matter what goes wrong with the pointing database read.

It should be replaced with `except pd.errors.DatabaseError`. According to [Pandas docs](https://pandas.pydata.org/docs/dev/reference/api/pandas.errors.DatabaseError.html) this error is thrown only when the SQL query is bad. Other errors will not be mistakenly caught by this clause.

**Comment by mschwamb** [comment]
do we care?  If there is any error we want to stop, right?
