### ISSUE TITLE
Sanity checks for orbits

### ISSUE THREAD

**Issue by bernardinelli** [dirac-institute/sorcha#1076]
The code should fail in these cases:
- e > 1 and a > 0 (unbound orbit with positive a is undefined)
- e < 1 and a < 0 (bound orbit is undefined with negative a)
- e == 1 in Keplerian elements (a is undefined)
- q<0 is undefined (q==0 is technically correct but weird?)
- e < 0 (undefined otherwise)

We should also check that:
- 0 <= inc <= 180 deg (rotations are defined otherwise but will be silly -- orbit will probably be mirrored?)
- 0 <= argPeri, node, M <= 360 deg OR -180 <= argPeri, node, M <= 180 deg (depends on our convention -- I will check). This is fine and the math will go through, just warn the user to make sure they're not doing something wrong

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Added input validation for orbit parameters to handle edge cases and undefined situations as described in the criteria. This includes checks for eccentricity, semi-major axis, perihelion distance, inclination, and angular parameters.

You can review changes in this commit: https://github.com/mnmnk43434/dirac-institute-sorcha-1076/commit/39fa34ba0d395883a479316e5872a28f51babae5.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by mschwamb** [comment]
What is this monstrosity that replied?

**Comment by astronomerritt** [comment]
This should probably be done in the OrbitAuxReader() class, in this method:

https://github.com/dirac-institute/sorcha/blob/e14fc7ff8cbee6653d31e5fe478d0d1080af77b9/src/sorcha/readers/OrbitAuxReader.py#L43-L117

**Comment by bernardinelli** [comment]
Does the code work if you input Keplerian elements for a hyperbolic orbit? (conversion from M -> Tp will yield a nan/complex number)

**Comment by mschwamb** [comment]
Should like we should just not let you put in hyperbolic as keplerian and require it in cometary or cartesian

**Comment by mschwamb** [comment]
fixed in  #1080
