### ISSUE TITLE
adding asteroid physical parameters (shapes, rotation)

### ISSUE THREAD

**Issue by garrettlevine96** [dirac-institute/sorcha#143]
Hi, I'm currently at the LSSC workshop at the CCA and have been speaking with Mario about adding some lightcurve data (shape, rotation, etc) to this post-processing pipeline. It would be great to talk about how I can get involved with this project. Thanks!

**Comment by mschwamb** [comment]
We have plans for this, but first we need a fully working version of the survey simulator. I don't think we'll have this in the first official release, but I expect the next public version shortly after.
