### ISSUE TITLE
Check which seeing (seeingFwhmGeom or seeingFwhmEff) should be used for trailing losses 

### ISSUE THREAD

**Issue by mschwamb** [dirac-institute/sorcha#158]
Check which seeing (seeingFwhmGeom or seeingFwhmEff) should be used for trailing losses and update PPTrailingLoss.py  as appropriate

**Comment by mschwamb** [comment]
seeingFwhmGeom is the one we should be using per Sam's conversations with LJ

**Comment by mschwamb** [comment]
Can you ask on lsst.community.org @samncorn ?

**Comment by mschwamb** [comment]
Detailed answer https://community.lsst.org/t/difference-between-seeingfwhmeff-and-seeingfwhmgeom/8137/2

**Comment by mschwamb** [comment]
@samncorn is going to check whether this is the case

**Comment by samncorn** [comment]
Okay, I think I finally have it figured out. Current version is correct, at least for the current trailing losses model.
