### ISSUE TITLE
Documentation changes

### ISSUE THREAD

**Issue by mschwamb** [dirac-institute/sorcha#332]
- Add scipy etc to conda environment setup for all the codes in the documentation
- Specify that we can only use spicepy < 5.0 for now
- add location of the test file to the demo documentation
- update what the command line arguments in

**Comment by drewoldag** [comment]
For reference - typically we use the Numpy docstring standard for python code. The guide is available here: https://numpydoc.readthedocs.io/en/latest/format.html#sections

A good reference inside of `sorcha` is the `.../src/readers/CSVReader.py` file: https://github.com/dirac-institute/sorcha/blob/main/src/sorcha/readers/CSVReader.py

**Comment by mschwamb** [comment]
Can close as now the readthedocs generates notebooks and the other information here is now likely irrelevant/being significantly updated. So this ticket can be closed for a rewrite of the documentation ticket that will be written shortly.
