### ISSUE TITLE
Remove objects that never anywhere close to getting bright enough to be detected 

### ISSUE THREAD

**Issue by mschwamb** [dirac-institute/sorcha#392]
From the ACM meeting - a way to cut down on what we're processing is to calculate the brightness of the ingested detections at their minimum distance if the object is far away from ever being detected, we should just cut them straight away rather than run through all the filters

**Comment by drewoldag** [comment]
Could be quickly pair coded. Basically we would just remove objects that are far too dim to be discovered.

**Comment by mschwamb** [comment]
Looks like we don't need this given the speed increases. Closing this for now as benchmarking will give us a better idea.
