### ISSUE TITLE
Automatically publish to PyPI when new version is tagged

### ISSUE THREAD

**Issue by drewoldag** [dirac-institute/sorcha#403]
There exists some mechanism for publishing to PyPI but it requires that someone manually edit the `ci.yml` file to do so (as near as I can tell). The LINCC Frameworks Python Project Template introduces an action that will publish automatically when a new tagged release is created. 

I would like to double check with the team that this approach is good, and ensure that we've got the correct API tokens created and stored as repo secrets to make use of the action.

**Comment by mschwamb** [comment]
as far as I know we never got to the stage of pypi. So I don't think there are any API tokens created or stored as repo secrets. Please feel free to set this up.

**Comment by drewoldag** [comment]
I can get this setup, but in order to finalize it, I'll need someone else on the science team to be a co-maintainer on the resulting PyPI package (I don't want to be the only admin for it 😄). All that I would need for that is the person's PyPI username I believe.

**Comment by mschwamb** [comment]
I have a feeling that needs to be me - I just made an account - mschwamb
