### ISSUE TITLE
Rename `surveySimPP` to `sorcha`.

### ISSUE THREAD

**Issue by drewoldag** [dirac-institute/sorcha#425]
Order of operations as advised by another LINCC Frameworks engineer who recently went through the renaming process. 
- [x] Find/replace uses in the codebase
- [x] Rename the repository
- [ ] Find/replace uses in the documentation

**Comment by mschwamb** [comment]
@drewoldag  In tests directory, there is surveySimPP that needs a rename:

https://github.com/dirac-institute/sorcha/tree/main/tests/surveySimPP
