### ISSUE TITLE
Refactoring lsstcomet into abstractlightcurve-ish class

### ISSUE THREAD

**Issue by mschwamb** [dirac-institute/sorcha#457]
Refactoring lsstcomet into abstractlightcurve-ish class

**Comment by mschwamb** [comment]
I've read through the lsstcomet class and In know the bits that are relevant we're using which is basically calculating the coma magnitude. Happy to hop on a call with you @drewoldag to pair code this.

**Comment by drewoldag** [comment]
A related issue is here: #501
