### ISSUE TITLE
Improve the linking filter - if that fails create quick and dirty SSP detection efficiency filter

### ISSUE THREAD

**Issue by mschwamb** [dirac-institute/sorcha#466]
Difi is slow but for most populations if there are enough chances you don't need to do it that thoroughly. So if there are enough observations for linking to happen at least once and over N years than we can say all the precovery would be done and find all detections on Rubin images. Then we would need to remove X% of objects based on the linking efficiency of SSP. 

How about @bernardinelli, @astronomerritt, and I sketch this out?

**Comment by mschwamb** [comment]
I think this is more complicated than what you wrote @astronomerritt .

This is on objects not observations now, but with some quick checks/cuts on the number/distribution of detections.    What happens if some object only has 2 tracklets and never got a third within 14 days? that wouldn't have been linked, but I think the above says it would be counted as a discovery if random_chance < linking_efficiency

**Comment by astronomerritt** [comment]
Ah, so you still want to keep _some_ of the linking filter checks in a sense?

I wonder if it can be done statistically by number of observations of the object. For example if we could determine that if an object is observed ~100 times it's 95% per cent likely to be linked but if it's observed 5 times that's 0%. Some testing might help us come up with an empirical function.

Alternatively we could check for at least six observations in 14 days, or more rigorously at least three tracklets in 14 days, but once we start introducing that rolling window the runtime tends to go up - at least it does when I do it!

**Comment by mschwamb** [comment]
Currently @mjuric  believe's that it's better to see if we can implement a full linking filter instead. So he's going to work on improving difi or adapting his version for linking for here.
