### ISSUE TITLE
Pull light curve class and utilities and lsst comet refactor out of sorcha repo 

### ISSUE THREAD

**Issue by mschwamb** [dirac-institute/sorcha#467]
Pull light curve class and utilities and lsst comet refactor ( #457) out of sorcha repo  and into https://github.com/dirac-institute/sorcha_communiity_utils/ . We will want that repo also set up with the python project template and read the docs to automatically generate demo notebooks

**Comment by drewoldag** [comment]
Some items associated with this: 

- [ ] Create scaffolding in sorcha_community_utils with PPT
- [ ] prefactor the existing lightcurve code in sorcha - fix docstrings, remove `lightcurve` config in favor of only one parameter
- [ ] Possibly rename `LightcurveImporter` module
- [ ] Make a call to `LightcurveImporter.update_lc_subclasses()` in sorcha to register the LC models just prior to use.
- [ ] Make sure that sorcha_community_utils is pip installable at least - it takes a dependency on `sorcha`.
