### ISSUE TITLE
Remove `lightcurve` boolean configuration parameter

### ISSUE THREAD

**Issue by drewoldag** [dirac-institute/sorcha#482]
There isn't a need for both a `lightcurve:bool` and a `lc_model:str` parameter in the configuration file. 

We should remove the boolean and assume that if the user passes `"none"`, `""`, or and unknown light curve model name, that we will not execute lightcurve model calculations.

**Comment by mschwamb** [comment]
Good catch. That was the original intention, but I might have missed in the approval that this wasn't the case
