### ISSUE TITLE
mag contribution from light curve is a contribution to the apparent mag but should not be introduced to H before calculating the phase curve

### ISSUE THREAD

**Issue by mschwamb** [dirac-institute/sorcha#483]
@bernardinelli I've been thinking more about light curves. I now remember light curves sit on top of the phase curve. All a light curve does is cause oscillations around the value on the phase curve.  So when we measure a phase curve, it's effectively light curve invariant if you have good enough sampling So we should be using H in calculating the apparent magnitude contribution due to the phase curve not a H+light curve modification which is now what sorcha does in. That's not correct. 

So I think here 

https://github.com/dirac-institute/sorcha/blob/8145f00930bfc409e53e7d61a37e72ee2e7db65b/src/sorcha/modules/PPCalculateApparentMagnitudeInFilter.py#L68

with H_eff switched to to H in the in between

Heff needs to be lc_contribution instead and then 

https://github.com/dirac-institute/sorcha/blob/8145f00930bfc409e53e7d61a37e72ee2e7db65b/src/sorcha/modules/PPCalculateApparentMagnitudeInFilter.py#L108C1-L108C81

Needs to have a lc_contribution added to it there.

**Comment by mschwamb** [comment]
It may be it turns into a linear offset anyway, but I think this implementation will be confusing to someone who is reading the code and does what I am doing wait the H was modified with the light curve before calculating the contributed from then phase function

**Comment by bernardinelli** [comment]
Yeah, the way you described is how I originally implemented it. The current phase curves we have do not actually care about `H`, they just care about the phase angles - so it doesn't matter from an implementation point of view. On  the philosophical side of the issue, I could argue both ways: eg imagine an ellipsoid rotating, it has a smaller/larger effective area => larger/smaller effective H at different points of the light curve. But also, as you say, with good enough sampling, they should decouple completely. Happy to change the implementation, but I don't know if we really need to :)

**Comment by mschwamb** [comment]
`On the philosophical side of the issue, I could argue both ways: eg imagine an ellipsoid rotating, it has a smaller/larger effective area => larger/smaller effective H at different points of the light curve.`

Yes I agree the effective H has changed with a light curve but since this is a simulation, the user is the all seeing/all knowing creator of their Solar System and so they've inputted an median H  in the physical parameter file and will have phase curve values on perfect knowledge of the light curve independent of the light curve oscillations. So we're going the other way where the phase curve is fully defined from the H median that is inputted by the user with the light curve fully characterized as well. 

I think this is the function grad students will look at and folks like me and if we struggle to read it there will be some confusion. So I agree although things should compute the same way, it would be better to use H instead of an effective H everywhere and then add the light curve enhancement to the apparent mag at the end. 

The cometary activity enhancement in apparent mag is going to be reworked to do the same. I know it's more complicated at the moment and not 100% correct. @astronomerritt is working on that change, so if you can make the change so it's apparent mag= apparent_mag_before_activity+ lc_contribution that would be great so that it's super clear to the reader. 

Sorry for the extra work.It dawned on my reading through everything cold and trying to see what everything was doing at 11pm at night to realize this required more thinking the way we've written it currently.

**Comment by astronomerritt** [comment]
I can go ahead and make this change if you like @bernardinelli - I'm making changes in that section of the code anyway.

**Comment by mschwamb** [comment]
@drewoldag  and I were pair coding today and the upcoming pull request  this change while addressing #457

**Comment by mschwamb** [comment]
That's pull request #508
