### ISSUE TITLE
use the astropy units and quantities for the value for au in km in PPCalculateApparentMagnitudeinFilter

### ISSUE THREAD

**Issue by mschwamb** [dirac-institute/sorcha#485]
Looking at  PPCalculateApparentMagnitudeinFilter, I see there's a conversion from km to au and it's using a long number to convert from km to au. Reading this one has to check what value this is. Astropy has a units and quantities and it seems better to use this rather than have random divide by 1.495978707e8 in the code 

One example:

https://github.com/dirac-institute/sorcha/blob/8145f00930bfc409e53e7d61a37e72ee2e7db65b/src/sorcha/modules/PPCalculateApparentMagnitudeInFilter.py#L52C1-L52C54

There are two other lines in that function that also divide by 1.495978707e8  

e.g 

>>> import astropy 
>>> from astropy import units as u
>>> x=1.0*u.au
>>> x.to(u.km)
<Quantity 1.49597871e+08 km>
>>> x.to(u.km).value
149597870.7

**Comment by mschwamb** [comment]
I also think it would be better to define those variable names so the units are clear r_au, delta_ra, etc . In the long term it will likely make our lives easier.

**Comment by bernardinelli** [comment]
Another option to avoiding adding an extra dependency (if astropy isn't already a dependency) would be to define the constants we care about somewhere (maybe a constants.py file), eg with an `AU_TO_KM = 1.495978707e8` variable

**Comment by mschwamb** [comment]
Astropy is already a dependency

**Comment by mschwamb** [comment]
Also in the comet magnitude function as well are these distances
