### ISSUE TITLE
Warn the user if the requested lightcurve model isn't found in `LC_METHODS`

### ISSUE THREAD

**Issue by drewoldag** [dirac-institute/sorcha#486]
If the user requests a lightcurve model that is not present in the LC_METHODS dictionary, we'll fail gracefully and continue on in the code. 

We should change that in one of two ways. Either expand the conditional in src/sorcha/modules/PPCalculateApparentMagnitudeInFilter.py so that there is some logging that is presented to the user. Or expand the logic in config parser script such that it will check for the existence of the lightcurve method before any calculations are made.

**Comment by mschwamb** [comment]
I think this check should happen in the config parser. Especially if the simulation is asking sorcha to run the ephemeris generation it could take a bit to get to the apparent magnitude function, and it would be better to fail and return an error early for issues with settings/configurations if possible

**Comment by mschwamb** [comment]
Also ditto for cometary activity model
