### ISSUE TITLE
add tests to ensure that the example config.ini files are up to date

### ISSUE THREAD

**Issue by maxwest-uw** [dirac-institute/sorcha#514]
with the number of changing run parameters we have sorcha, as well as the multiple `.ini` files we use to run various benchmarks and e2e tests, it would be nice to have a small set of validation tests to make sure that these files are up to date. I've run into the problem a couple times where we've added a new required parameter but it wasn't updated uniformly across all our files, causing a benchmark run to fail.

**Comment by mschwamb** [comment]
I think this is covered by the new demo command test as if the config file is incorrect it will either throw an error or there will be no output which should trigger an issue with the demo command test. I will get a double check that this is true.
