### ISSUE TITLE
Swap ObsCodes.txt to MPC JSON, download it, and edit reader to read in the json

### ISSUE THREAD

**Issue by mschwamb** [dirac-institute/sorcha#517]
ObsCodes.txt is stolen from copying the website human readable form on the Minor Planet Center website. The MPC does provide that for download. I just learned there is a json version of the file that can be downloaded from https://minorplanetcenter.net/Extended_Files/obscodes_extended.json.gz . I imagine in the long term the MPC will definitely continue to support json file. I think it would be good to using pooch to download this json file and update the Observatory class to read in and parse the json file instead

**Comment by mschwamb** [comment]
Note this is lower priority. If it's easier to get everything running with the .txt first. Do that.

**Comment by mschwamb** [comment]
Note - this file changes every few weeks as other observatories are added so I don't think you'll want to do a checksum for this file.

**Comment by drewoldag** [comment]
This has been taken care of in #516. Specifically implemented in this commit: https://github.com/dirac-institute/sorcha/pull/516/commits/3f0617b477194f40ef4e57708506989b6b587ddb

**Comment by mschwamb** [comment]
I remember your ticket. We have been having the same problem internally. We have a repository that needs to download the obscode file and we were trying to download it from the website and the download was failing. We had to change our unit tests to make it work.

We have tried to investigate the problem, but it is not clear to us why this is happening. It might be due to how GitHub is trying to download the file, but unfortunately I can’t give you more information because we don’t really know. As you said, it works perfectly fine on every single machine or server. 

This is what we did to solve the problem, in case it helps:

    We keep a copy of the obscode file in our unit tests directory
    We try to download the file multiple times with a 2 seconds delay between attempts
    It they all fail, we use the old copy of the obscode file. 
    This is good enough for testing on our side.
    We regularly update the obscode file copy on our unit tests directory.

We can try and investigate further, but I’m not sure how long it will take us to find the issue. We will also think about possible alternatives.

**Comment by mschwamb** [comment]
I'll also chime in and say that it is fairly widely regarded that it is bad practice to make your CI dependent on any external data source.
As per Federica's response, we ran up against this ourselves, and learned the hard way.

Suggested alternatives to direct requests of an external website include, but are not limited to: 

Mocking/Stubs: Use mocking or stubs for external services. This way, you simulate the external service within your test environment. Libraries such as unittest.mock in Python or equivalents in other languages can be used to replace actual HTTP calls with predefined responses.

Local Test Data: If possible, download a snapshot of the necessary data from the external resource and include it in your test suite as a fixture. This ensures that your tests are not dependent on the network or the external site's availability. In your case it should not matter that the obs code file you use for tests is potentially out-of-date because (presumably) any obs-codes you use in your tests will be of the same vintage as the obs-code file itself.
