### ISSUE TITLE
Ensure that the extra data files for REBOUND+ASSIST can be downloaded into a user specified folder 

### ISSUE THREAD

**Issue by mschwamb** [dirac-institute/sorcha#518]
@drewoldag  you might already be doing this in #516 but I wanted to raise it here so you have my thinking 

However the JPL and spice kernels are downloaded and install, I wanted to make sure the user can specify the directory these files are in and download them once post install. 

I can see a situation where a user was running with one set of spice kernels, nukes their conda environment and reinstalls. If at runtime these are being installed there could be an issue  If the spice kernels changed for some reason, the user won't know know that. Same thing if someone has to install the software separately onto a new computer in their cluster. The user will do a conda install/pip install and think things are the same as long as they install the same version of sorcha.  

If it's a folder where all of these are stored and the user specifies in the config file where these files are at least the user can copy over their spice kernels folder and things would be the same on the different installs.

There other problem could be quotas on super computers. Steph, I think hit this with Kelvin (the Queen's super computer). That their conda install was going over the home directory quota. So having the ability to store these files in a folder outside the python install like on a scratch disk on each node or a shared scratch disk ( wherever the user needs them to be) might be a better way to go.

**Comment by mschwamb** [comment]
naif0012.tls is the leap second file.  This changes whenever there is a new leap second.  The last was in 2017.
earth_720101_070426.bpc is the historical Earth orientation specification.  This should not change, unless there is a new model.
earth_200101_990628_predict.bpc is a prediction of the Earth's future orientation.  Likewise, this should not change.
pck00010.tpc contains orientation information and physical constants for other bodies.  This should only change rarely.
de440s.bsp gets used for getting the Earth's position for ephemerides.  
earth_latest_high_prec.bpc is a regularly updated specification of the Earth's orientation, refined as new observations are incorporated.  This will supersede the other specification if loaded after the previous predictive model.

**Comment by drewoldag** [comment]
This is taken care of in #516 - the user now has access to a utilities script that provides two input arguments: 

- `--cache` - to define the location where the downloaded files will be stored
- `-f`, `--force`, - remove any previously downloaded files in the the --cache directory and redownload.
