### ISSUE TITLE
Swap constants in ephemeris generator to astropy constants and units

### ISSUE THREAD

**Issue by mschwamb** [dirac-institute/sorcha#519]
Once everything is working, we should standardize the standards and use astropy [units](https://docs.astropy.org/en/stable/units/) and [constants](https://docs.astropy.org/en/stable/constants/index.html) classes. Either remove [simulation_constants.py ](https://github.com/dirac-institute/sorcha/blob/f093aae8b8d30dc8a2380d8711034089ac1b16ee/src/sorcha/ephemeris/simulation_constants.py)and insert these values directly into the other files or swap those values in simulation_constants.py to using the astropy classes 

from astropy import units as u

x=1.0*u.au
x.to(u.km)
<Quantity 1.49597871e+08 km>
x.to(u.km).value
149597870.7

Where au_km is used substitute with x.to(u.km).value or (1.0*u.au).to(u.km).value

au_m = (1.0*u.au).to(u.m).value

Rearth_km can be written as  1.0*u.R_earth).to(u.km).value

from astropy.constants import c

speed_of_light=c.value*86400/au_m # au per day

I am not sure what units GM_sun is in. @matthewholman can add some clarity here

**Comment by matthewholman** [comment]
The units for ASSIST are au, solar masses, and days.  I believe most of the constants can be read from the ephemeris files, although I haven't been fastidious about doing that.

**Comment by mschwamb** [comment]
Let's hold off on implementing this until everything is validated and then there can be a discussion if this should be done. It may be better to leave the constants as is.

**Comment by matthewholman** [comment]
I agree.

**Comment by mschwamb** [comment]
Given the validation, at this point I don't think there's a need to change these values here. In the rest of postprocessing steps it makes sense to use astropy units.
