### ISSUE TITLE
ensure all required values are computed from ephemeris generator and sent back to sorcha's post processing part

### ISSUE THREAD

**Issue by mschwamb** [dirac-institute/sorcha#524]
When hooking up the ephemeris generator to the rest of sorcha we need to set up the data structure for the ephemeris in the same way as is currently readin from the OIF produced files

OIF had these columns:

AstRange(km),AstRangeRate(km/s),AstRA(deg),AstRARate(deg/day),AstDec(deg),AstDecRate(deg/day),Ast-Sun(J2000x)(km),Ast-Sun(J2000y)(km),Ast-Sun(J2000z)(km),Ast-Sun(J2000vx)(km/s),Ast-Sun(J2000vy)(km/s),Ast-Sun(J2000vz)(km/s),Obs-Sun(J2000x)(km),Obs-Sun(J2000y)(km),Obs-Sun(J2000z)(km),Obs-Sun(J2000vx)(km/s),Obs-Sun(J2000vy)(km/s),Obs-Sun(J2000vz)(km/s),Sun-Ast-Obs(deg)

We need the phase angle (Sun-Ast-Obs(deg)) and these other distances, and rates for calculating trailing losses. 

The current Jupyter notebook for the ephemeris generator I think calculates most of these things. Currently the output command has               
 
`  outstring = '%lf %lf %s %s %f %f %lf\n' % (jd_tdb, mjd_tai, utc_str, k, ra0, dec0, ang_from_center)`

@matthewholman  Can you point out which other variables in your notebook should be outputted in order to match the OIF outputted values?

**Comment by matthewholman** [comment]
@mschwamb Yes, most of those quantities are already computed in the steps of getting the RA/Dec values.  Getting the RA/Dec rates will take a little more work, but I can do that.

**Comment by mschwamb** [comment]
Thanks @matthewholman . I think it will be next thing after getting the notebook  into the source code and checking the values match the notebook will be hooking in the post processing bits since y'all are working on comparing and developing the orbit conversions.

If you can point out in this ticket when you have time which variables in the notebook  match the above quantities that would be a really helpful starting pointing. Max and Drew can fake the RA/Dec rates until you have have them.
