### ISSUE TITLE
Add logging and error logging calls to the new ephemeris generator bits

### ISSUE THREAD

**Issue by mschwamb** [dirac-institute/sorcha#525]
Go through and check where we want to output to the run log and the error log in the new ephemeris generator bits and pieces

**Comment by mschwamb** [comment]
If someone gets the verbose log setup in ephemeris driver I can add the output statements to the log

**Comment by astronomerritt** [comment]
My recent PR sets this up. If you want to add more log messages:

```
verboselog("This prints a message to the info log if verbose == True.")
args.pplogger.info("This forces a log message to the info log.")
args.pplogger.error("This prints a message to the error log.")
```

Adding logging to _another_ function is as simple as making sure args is passed to that function, then to enable verbose logging, add at the top of the function:

`verboselog = args.pplogger.info if args.verbose else lambda *a, **k: None`

You can see how I've done this at the top of `create_ephemeris`.
