### ISSUE TITLE
Add in some command line argument parameter for input file directory path

### ISSUE THREAD

**Issue by mschwamb** [dirac-institute/sorcha#542]
Running sorcha not in the directory where my input files are means really long paths.

sorcha -c /Users/mschwamb/PPConfig_test.ini -p /Users/mschwamb/Research/sorcha/sorcha/demo/sspp_testset_colours.txt -o /Users/mschwamb/Research/sorcha/sorcha/demo/sspp_testset_orbits.des -e /Users/mschwamb/Research/sorcha/sorcha/demo/example_oif_output.txt -u /Users/mschwamb/ -t testrun_e2eq

 Can we add in a command line argument for input file directory in case the user wants to use the same folder/path for all input files?

**Comment by mjuric** [comment]
Playing with an alternative -- how does this look like?

```
cd /Users/mschwamb/Research/sorcha/sorcha/demo/ &&
sorcha -c ~/PPConfig_test.ini -p sspp_testset_colours.txt -o sspp_testset_orbits.des -e example_oif_output.txt -u /Users/mschwamb/ -t testrun_e2eq
```
