### ISSUE TITLE
Have the entire config file read in outputted to the log file?

### ISSUE THREAD

**Issue by mschwamb** [dirac-institute/sorcha#543]
Right now sorcha outputs into the logfile what it believes is the input configuration file. But if I come back six months later and lost my config file I have to reconstruct it from the log output. Should the log file output every row of then config file as well so we have a preserved copy of it?

**Comment by jeremykubica** [comment]
In the past I've used source control for this: treat the configurations like code and add them to source control, version them, etc. However that might not be a useful workflow for Sorcha's users.

**Comment by mschwamb** [comment]
Talking with Mario I think we'll want to print line by line to the log file. Basically as a backup so we have it.
