### ISSUE TITLE
Should logging start earlier?

### ISSUE THREAD

**Issue by mschwamb** [dirac-institute/sorcha#544]
If you screw up some command line arguments there is no change to the error log. Should logging start earlier?

**Comment by jeremykubica** [comment]
I would say yes. `PPCommandLineParser` outputs to the logs before they are set up. Along the lines of #543, earlier logging would also allow Sorcha to log the command line arguments.

**Comment by mschwamb** [comment]
Thanks. @jeremykubica, do you want to implement this?

**Comment by jeremykubica** [comment]
Yes. I can take this one.
