### ISSUE TITLE
Ensure we're testing sorcha on multiple systems/operating systems 

### ISSUE THREAD

**Issue by mschwamb** [dirac-institute/sorcha#550]
It would be good to ensure that were testing sorcha's unit tests on multiple systems/operating systems 
linux, mac osx arm64 and also intel macs.

**Comment by drewoldag** [comment]
Currently our unit tests run on `ubuntu-latest` and `macos-latest` operating systems. 

The details can be seen here: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

Basically this documentation indicates that the GitHub hosted runners that are used to execute the CI currently doesn't include ARM processors. However, I found this in the GitHub product roadmap: https://github.com/github/roadmap/issues/528

It's already been pushed out at least 1 quarter, but if it doesn't get pushed again, then some time in Q4, we may be able to specify mac M1 hardware for running tests.

**Comment by mschwamb** [comment]
Leaving this so when Apple Silicon becomes available that we add it for the unit tests to run on

**Comment by mschwamb** [comment]
Looks like this is now available in beta for the larger runner https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/

**Comment by drewoldag** [comment]
I'm sure that you're already aware, but these are not free runners. In the blog post it calls out: "With today’s launch, our macOS larger runners will be priced at $0.16/minute for XL and $0.12/minute for large."

**Comment by mschwamb** [comment]
Yep. No plan to implement. Just updating the ticket with the latest info.

**Comment by mjuric** [comment]
Actually. we're already supposed to have this (I knew I set this up...). Looks like it's a GitHub issue -- I'll ping support.

<img width="328" alt="image" src="https://github.com/dirac-institute/sorcha/assets/620059/d7b0a558-c99b-430a-8bba-771f63ee2fc6">

**Comment by drewoldag** [comment]
Neato

**Comment by mschwamb** [comment]
I was secretly hoping this was the case....

**Comment by mjuric** [comment]
Ticket [opened](https://support.github.com/ticket/personal/0/2372291).

And the [PR is here](https://github.com/dirac-institute/sorcha/pull/701), for when it gets resolved.

**Comment by mschwamb** [comment]
macos-14 is available  which is a runner for Mac M1 - we're getting HDF5 errors. It's a configuration thing, but I am not 100% sure how to fix it with pip. I fix it by conda installing the package and then the libraries and environmental variables are correct
