### ISSUE TITLE
Calculate GMsun from DE440/441

### ISSUE THREAD

**Issue by mschwamb** [dirac-institute/sorcha#570]
Use spiceypy to calculate GMSun from DE440/441 . If that's not possible check and throw error if DE440/441 is not being used as the GMsun value is incorrect.

**Comment by matthewholman** [comment]
I can get ASSIST to return the GMsun value.  Would that be fine?

**Comment by mschwamb** [comment]
Sure. As long as we can get the value

**Comment by matthewholman** [comment]
This will work:
GMsun = ephem.get_particle('Sun', 0).m

The second argument to get_particle is the time, which doesn't matter if you just want the mass.

**Comment by mschwamb** [comment]
Thanks @matthewholman Can you recommend  how to implement that into the[ generate_simulation function](https://github.com/dirac-institute/sorcha/blob/4fe07d831636ca6ccf91da3ffb9571d6d5ed7af8/src/sorcha/ephemeris/simulation_setup.py#L76) or  [parse_orbit_row](https://github.com/dirac-institute/sorcha/blob/4fe07d831636ca6ccf91da3ffb9571d6d5ed7af8/src/sorcha/ephemeris/simulation_parsing.py#L19) function?

**Comment by matthewholman** [comment]
If it seems ok to do, how about putting 
GMSUN = ephem.get_particle('Sun', 0).m toward the top of simulation_parsing.py?  Either that or put in a file dealing with constants.   We want to avoid unnecessary, repeated calls to get_particle().

**Comment by mschwamb** [comment]
Ah okay. Then maybe it goes in https://github.com/dirac-institute/sorcha/blob/4fe07d831636ca6ccf91da3ffb9571d6d5ed7af8/src/sorcha/ephemeris/simulation_constants.py

**Comment by matthewholman** [comment]
Where do we first instantiate the ephemeris?

**Comment by mschwamb** [comment]
I think it's going to be helpful for Drew and Max if they are told where exactly this call needs to go. Can it be put into here where the planets are initialized? and just have [this function ](https://github.com/dirac-institute/sorcha/blob/4fe07d831636ca6ccf91da3ffb9571d6d5ed7af8/src/sorcha/ephemeris/simulation_setup.py#L21)that initializes the ephem structure also return back the GMSun value?
