### ISSUE TITLE
Are we keeping difi functionality as an option if we have minidifi working?

### ISSUE THREAD

**Issue by mschwamb** [dirac-institute/sorcha#579]
Currently the old linking filter function calling difi is now PPLinkingFilter_OLD. Do we want to keep it and resurrect it as another option the user could use. Once we're happy with validation?

**Comment by mjuric** [comment]
I just left a note about that [here](https://github.com/dirac-institute/sorcha/pull/566#issuecomment-1703332471).

**Comment by mschwamb** [comment]
Will leave this here, so we remember to deal with it later and not forget.

**Comment by mschwamb** [comment]
We will test out minidif and then fully remove difi. So this can be closed. It's not a question anymore. More a validation task.
