### ISSUE TITLE
Low trailed source mags with high magnitude MBAs

### ISSUE THREAD

**Issue by Gerenjie** [dirac-institute/sorcha#580]
Pedro, Mario, and I found some DP0.3 detections with very very high (at least one >40) listed magnitude in SurveySimPP output. If I remember correctly, this can occur when trailed source magnitudes are ~20 while normal magnitudes are much higher, and occurs even for some MBAs and maybe TNOs. Without Epyc I can't provide a source input+output that produces such a magnitude, but I see ~1 detection with m>30 for each output detection in general in DP0.3, so I think it should be relatively easy to reproduce.

**Comment by mschwamb** [comment]
Can you provide the orbit from DP0.3 and IDs at least we can check the trailing calculation?

**Comment by mschwamb** [comment]
DP0.3 SSO ids for asteroids that have odd PSF mags 
[extreme_mag_sso_ids.txt](https://github.com/dirac-institute/sorcha/files/12903895/extreme_mag_sso_ids.txt)

**Comment by mschwamb** [comment]
@Gerenjie is going to send Mario test inputs

**Comment by mschwamb** [comment]
In a chat with Steph today, we think this might be a residual from the UW group running an older version of surveysimPP. There was an issue where if we don't get SNR < 2 objects then when applying random errors things would pop up with detections that trailed source mags that shouldn't be detected by PSF mags that were bright enough to be detected when applying uncertainties with the random number generator. It was corrected, but it might have been DP0.3 was run with the version that didn't have this fix. Steph is confirming if the 10 year run they have produced has any of these pathological objects and will email @Gerenjie  about what version of the code was used on DP0.3

**Comment by mschwamb** [comment]
DP0.3 was run without the SNR < 2 cut. This was the source of the problem. It's been confirmed this issue is not popping up in the runs using the current codebase,
