### ISSUE TITLE
update columns for A+R output

### ISSUE THREAD

**Issue by mschwamb** [dirac-institute/sorcha#594]
From Steph:

 A+R output, the columns for AstRA(deg) and AstRARate(deg/day) have been switched. RA is in the RA rate column and vice versa. Same with AstDec(deg) and AstDecRate(deg/day).

**Comment by drewoldag** [comment]
I'm looking at the output from A&R on my local machine, and I can see what @astronomerritt is reporting. Indeed the values for `AstRA(deg), AstRARate(deg/day)` and `AstDec(deg), AstDecRate(deg/day)` seem to be switched. Given that the file is written out in this way indicates that the starting point of the investigation should be here: 
https://github.com/dirac-institute/sorcha/blob/main/src/sorcha/ephemeris/simulation_driver.py#L139
