### ISSUE TITLE
clarify time units 

### ISSUE THREAD

**Issue by mschwamb** [dirac-institute/sorcha#599]
Based on a chat with @matthewholman: Given the whole in email discussion about time and which definition we're using where, we're going to want to clearly enforce what we're defining time as. So everywhere we're going to want to change these two variables: 

observationStartMJD --> observationStartMJD_TAI
FieldMJD --> FieldMJD_TAI

**Comment by drewoldag** [comment]
@mschwamb pretty sure I know the answer to this, but... for the variable renaming issues (#608 and #609 too) does the renaming apply to all instances of this name showing up, including the input files? 

For instance, should I anticipate renaming the column in `.../demo/mba_sample_1000_eph.csv` from `FieldMJD` to `FieldMJD_TAI`? 

I guess the question here is, can I almost blindly find-and-replace? 😃

**Comment by drewoldag** [comment]
To update the various sqlite databases: 

```
>>> import sqlite3
>>> con = sqlite3.connect('./demo/oneline_v2.0.db')
>>> cur = con.cursor()
>>> cur.execute("select sql from sqlite_schema where name='observations'")
>>> cur.fetchall()
<output>

>>> cur.execute("alter table observations rename column 'observationStartMJD' to 'observationsStartMJD_TAI'")
>>> cur.fetchall()
<no output>
```

**Comment by mschwamb** [comment]
We can't cheat and update the sqlite databases, because we get those from Rubin and so they will always for now at least have observationStartMJD . So that going to observationStartMJD_TAI  has to happen in the code after read in of the pointing database, changing the header of the column of the pandas dataframe in sorcha to  observationStartMJD_TAI. 

FieldMJD_TAI is pretty much a find and replace for ephemeris generation and checking that if we read in an external file we force it to have  FieldMJD_TAI, so yes these input files for tests and in the demo folder need to change

**Comment by mschwamb** [comment]
So .../demo/mba_sample_1000_eph.csv gets the header updated, but the pointing databases ./demo/oneline_v2.0.db does not change. It is a double standard, but I think most users will want to download the rubin_sim simulated pointing database. Since they don't generate that unlike all the other input files, I think it's better that we do the change after read in for that one.

**Comment by drewoldag** [comment]
To address the `observationStartMJD` -> `observationStartMJD_TAI`, I've updated the sql queries to be roughly: 
` select ... observationStartMJD as observationStartMJD_TAI, ... order by observationStartMJD_TAI`. 

Plus a few changes in the code where the Pandas dataframe column was being reference by name have been changed.
