### ISSUE TITLE
ccdVisitID

### ISSUE THREAD

**Issue by Gerenjie** [dirac-institute/sorcha#600]
Although the CCD on which chip each detection falls is calculated at some point, it is not outputted. Having this as an (optional) output would allow us to properly populate the ccdVisitID column the DiaSource table.

**Comment by mschwamb** [comment]
@samncorn  has this functionality already in the camera CCD association function but we don't have this enabled. First we need to check that the naming scheme is the same for the real LSSTCam.

**Comment by samncorn** [comment]
I think the current implementation is incorrect, so until I can verify it the values returned for which detector a detection is on should be disregarded.
