### ISSUE TITLE
no output from ephemeris generation to the rest of sorcha

### ISSUE THREAD

**Issue by mschwamb** [dirac-institute/sorcha#631]
sorcha -c ./demo/sorcha_config_demo.ini -p ./demo/sspp_testset_colours.txt -ob ./demo/sspp_testset_orbits.des  -pd ./demo/baseline_v2.0_1yr.db -o ./ -t testrun_e2e -f 

if I delete the offending lines that are causing #627, I get like nothing is being returned to the rest of sorcha from ephemeris generation when I was getting output yesterday from the same command

**Comment by mschwamb** [comment]
I see an ephemeris file is made if I provide the -ew flag, but the output I was seeing in  testrun_e2e.csv does not exist anymore. 

sorcha -c ./demo/sorcha_config_demo.ini -p ./demo/sspp_testset_colours.txt -ob ./demo/sspp_testset_orbits.des  -pd ./demo/baseline_v2.0_1yr.db -o ./ -t testrun_e2e -f  -ew ephemeris.csv

**Comment by mschwamb** [comment]
sorcha -c ./demo/config.txt -p ./demo/sspp_testset_colours.txt -ob ./demo/sspp_testset_orbits.des -pd ./demo/baseline_v2.0_1yr.db -o ./ -t testrun_e2e -f -ew ephemeris.csv

should produce files like
[ephemeris_output.csv](https://github.com/dirac-institute/sorcha/files/12614332/ephemeris_output.csv)
[testrun_e2e.csv](https://github.com/dirac-institute/sorcha/files/12614333/testrun_e2e.csv)

using  demo/config.txt (note this still has the flag removed today for the simulations because this was running on the version that made a csv file and read it. 

[config.txt](https://github.com/dirac-institute/sorcha/files/12614334/config.txt)

Now when I run with this same set of object and orbits, testrun_e2e does not exist

**Comment by mschwamb** [comment]
now running today with the full merge of ephemeris generation there is nothing outputted [testrun_e2e.csv](https://github.com/dirac-institute/sorcha/files/12614333/testrun_e2e.csv) does. not exist

**Comment by mschwamb** [comment]
Posted on slack, but adding here from completeness.

If I read the ephemeris file back in via -er command that is generated with the -ew command in a previous run, then I get output. The reader function is doing something to the dataframe I think or not doing something to the dataframe

**Comment by drewoldag** [comment]
I left a long description of the problem in slack, but I'll include a summary here as well. 

> In `simulation_driver.py`, when the "join on" column types of the `ephemeris_df` and `orbits_df` dataframes were of dissimilar types, the join would fail silently, resulting in an output dataframe with the correct columns, but the right side of the join would be all `NaN`.
Initially an unsuccessful attempt was made to force the column types to match, but type change was transient, and reverted prior to performing the join. Additionally, it swallowed any exceptions that might have been raised.
The solution forces the column types for both dataframes to be Python string, which seems to be the most natural data type available for object id.
