### ISSUE TITLE
make a separate function for calculating ancillary ephemeris values and split other code blocks into functions

### ISSUE THREAD

**Issue by mschwamb** [dirac-institute/sorcha#638]
it would be good to get these lines into its own function:

https://github.com/dirac-institute/sorcha/blob/1a4dec869f71886651d5a3dfd087547f5b39d617/src/sorcha/ephemeris/simulation_driver.py#L106C1-L149C22

**Comment by mschwamb** [comment]
It would be good to have a unit test here as well for this new function

**Comment by mschwamb** [comment]
@drewoldag  while you're working on that .py, do you also want to stick in a separate function that bit the loop that has "this should be a separate function" bit ?

```
        # This should be a separate function
        desigs = set()
        for pix in pointing["pixels"]:
            desigs.update(pixel_dict[pix])
```

**Comment by drewoldag** [comment]
Sure, I can pull that out in a distinct function.

**Comment by drewoldag** [comment]
I spent a little time looking at the snippet above in the code base, and I'm not sure there's a lot of value in pulling that out into a separate function. 

I would be more inclined to add a comment around it clarify its functionality, and then write some tests around `update_pixel_dict` function which provides the `pixel_dict` dictionary that is being used to populate the `desigs` set.

**Comment by drewoldag** [comment]
After conversation with @mschwamb, we'll add a comment around the `desigs` loop save the unit tests for a new issue.
