### ISSUE TITLE
Seg faults with running test sets - depending on what version of rebound install on mac

### ISSUE THREAD

**Issue by mschwamb** [dirac-institute/sorcha#641]
With v>=3.27 of rebound installed for a macosx_11_0_arm64

 sorcha -c ./demo/sorcha_config_demo.ini -p ./demo/sspp_testset_colours.txt -ob ./demo/sspp_testset_orbits.des -pd ./demo/baseline_v2.0_1yr.db -o ./ -t testrun_e2e -ar ./ar_files -f
Fatal Python error: Bus error

Current thread 0x00000001fc062080 (most recent call first):
  File "/Users/mschwamb/mambaforge/envs/sorcha/lib/python3.10/site-packages/assist/extras.py", line 44 in integrate_or_interpolate
  File "/Users/mschwamb/Research/python/lsst/survey_simulator/sorcha/sorcha/src/sorcha/ephemeris/simulation_driver.py", line 195 in update_pixel_dict
  File "/Users/mschwamb/Research/python/lsst/survey_simulator/sorcha/sorcha/src/sorcha/ephemeris/simulation_driver.py", line 84 in create_ephemeris
  File "/Users/mschwamb/Research/python/lsst/survey_simulator/sorcha/sorcha/src/sorcha/sorcha.py", line 183 in runLSSTSimulation
  File "/Users/mschwamb/Research/python/lsst/survey_simulator/sorcha/sorcha/src/sorcha/sorcha.py", line 489 in main
  File "/Users/mschwamb/mambaforge/envs/sorcha/bin/sorcha", line 8 in <module>

Extension modules: numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, erfa.ufunc, scipy._lib._ccallback_c, scipy.special._ufuncs_cxx, scipy.special._ufuncs, scipy.special._specfun, scipy.special._comb, scipy.linalg._fblas, scipy.linalg._flapack, scipy.linalg.cython_lapack, scipy.linalg._cythonized_array_utils, scipy.linalg._solve_toeplitz, scipy.linalg._decomp_lu_cython, scipy.linalg._matfuncs_sqrtm_triu, scipy.linalg.cython_blas, scipy.linalg._matfuncs_expm, scipy.linalg._decomp_update, scipy.sparse._sparsetools, _csparsetools, scipy.sparse._csparsetools, scipy.sparse.linalg._isolve._iterative, scipy.sparse.linalg._dsolve._superlu, scipy.sparse.linalg._eigen.arpack._arpack, scipy.sparse.csgraph._tools, scipy.sparse.csgraph._shortest_path, scipy.sparse.csgraph._traversal, scipy.sparse.csgraph._min_spanning_tree, scipy.sparse.csgraph._flow, scipy.sparse.csgraph._matching, scipy.sparse.csgraph._reordering, scipy.linalg._flinalg, scipy.special._ellip_harm_2, scipy.integrate._odepack, scipy.integrate._quadpack, scipy.integrate._vode, scipy.integrate._dop, scipy.integrate._lsoda, scipy.optimize._minpack2, scipy.optimize._group_columns, scipy._lib.messagestream, scipy.optimize._trlib._trlib, numpy.linalg.lapack_lite, scipy.optimize._lbfgsb, _moduleTNC, scipy.optimize._moduleTNC, scipy.optimize._cobyla, scipy.optimize._slsqp, scipy.optimize._minpack, scipy.optimize._lsq.givens_elimination, scipy.optimize._zeros, scipy.optimize.__nnls, scipy.optimize._highs.cython.src._highs_wrapper, scipy.optimize._highs._highs_wrapper, scipy.optimize._highs.cython.src._highs_constants, scipy.optimize._highs._highs_constants, scipy.linalg._interpolative, scipy.optimize._bglu_dense, scipy.optimize._lsap, scipy.spatial._ckdtree, scipy.spatial._qhull, scipy.spatial._voronoi, scipy.spatial._distance_wrap, scipy.spatial._hausdorff, scipy.spatial.transform._rotation, scipy.optimize._direct, astropy.time._parse_times, astropy.table._column_mixins, astropy.table._np_utils, yaml._yaml, astropy.io.ascii.cparser, astropy.utils.xml._iterparser, astropy.io.fits._utils, astropy.io.fits._tiled_compression._compression, astropy.io.votable.tablewriter, astropy.wcs._wcs, scipy.interpolate._fitpack, scipy.interpolate.dfitpack, scipy.interpolate._bspl, scipy.interpolate._ppoly, scipy.interpolate.interpnd, scipy.interpolate._rbfinterp_pythran, scipy.interpolate._rgi_cython, _brotli, astropy.stats._stats, astropy.stats._fast_sigma_clip, bottleneck.move, bottleneck.nonreduce, bottleneck.nonreduce_axis, bottleneck.reduce, astropy.timeseries.periodograms.lombscargle.implementations.cython_impl, astropy.timeseries.periodograms.bls._impl, synphot.synphot_utils, pandas._libs.tslibs.np_datetime, pandas._libs.tslibs.dtypes, pandas._libs.tslibs.base, pandas._libs.tslibs.nattype, pandas._libs.tslibs.timezones, pandas._libs.tslibs.ccalendar, pandas._libs.tslibs.fields, pandas._libs.tslibs.timedeltas, pandas._libs.tslibs.tzconversion, pandas._libs.tslibs.timestamps, pandas._libs.properties, pandas._libs.tslibs.offsets, pandas._libs.tslibs.strptime, pandas._libs.tslibs.parsing, pandas._libs.tslibs.conversion, pandas._libs.tslibs.period, pandas._libs.tslibs.vectorized, pandas._libs.ops_dispatch, pandas._libs.missing, pandas._libs.hashtable, pandas._libs.algos, pandas._libs.interval, pandas._libs.lib, pandas._libs.hashing, pandas._libs.tslib, pandas._libs.ops, numexpr.interpreter, pandas._libs.arrays, pandas._libs.sparse, pandas._libs.reduction, pandas._libs.indexing, pandas._libs.index, pandas._libs.internals, pandas._libs.join, pandas._libs.writers, pandas._libs.window.aggregations, pandas._libs.window.indexers, pandas._libs.reshape, pandas._libs.groupby, pandas._libs.testing, pandas._libs.parsers, pandas._libs.json, numba.core.typeconv._typeconv, numba._helperlib, numba._dynfunc, numba._dispatcher, numba.core.runtime._nrt_python, numba.np.ufunc._internal, numba.experimental.jitclass._box, matplotlib._c_internal_utils, PIL._imaging, matplotlib._path, kiwisolver._cext, matplotlib._image, healpy._healpy_sph_transform_lib, healpy._sphtools, healpy._pixelfunc, healpy._query_disc, healpy._masktools, healpy._hotspots, healpy._line_integral_convolution, _cffi_backend (total: 166)
zsh: bus error  sorcha -c ./demo/sorcha_config_demo.ini -p ./demo/sspp_testset_colours.txt -o
mschwamb@cider:~/Research/python/lsst/survey_simulator/sorcha/sorcha$ 

I get no issues if I pip install version 3.26.3

**Comment by mschwamb** [comment]
This is at least repeatable on M1/M2 macs - I find now that if I conda or pip install 3.26.3 of rebound I have a working version

This seems to cause seg faults on intel macs

**Comment by mschwamb** [comment]
@mjuric reinstalled the sorcha conda env with:
mamba create -n sorcha -c conda-forge numpy numba pandas=2.1 scipy astropy matplotlib sbpy pytables spiceypy healpy rebound pooch tqdm h5py python=3.10
then installed sorcha with:
pip install -e .
then commented out a line in sorcha/src/sorcha/modules/PPLinkingFilter.py that removes a stray remaining import of difi . Then ran:
sorcha -c ./demo/sorcha_config_demo.ini -p ./demo/sspp_testset_colours.txt -ob ./demo/sspp_testset_orbits.des -pd ./demo/baseline_v2.0_1yr.db -o ./ -t testrun_e2e
and then... it worked! (edited) 

, I also edited pyproject.toml as follows:
 dynamic = ["version"]
 dependencies = [
-    "numpy==1.24.3",
-    "pandas<2.1",
+    "numpy>=1.24.3",
+    "pandas>=2.1",
     "scipy",
     "astropy",
     "matplotlib",
     "sbpy",
     "tables",
-    "difi == 1.2rc3",
+#    "difi == 1.2rc3",
     "spiceypy",
     "healpy",
     "assist",

@mschwamb  (yeah referring to myself in third person - just easier so we know who's talking in each bit) 
I get a seg fault

seg fault
Current thread 0x00000001e88de080 (most recent call first):
 File "/Users/mschwamb/mambaforge/envs/sorcha/lib/python3.10/site-packages/assist/extras.py", line 44 in integrate_or_interpolate
 File "/Users/mschwamb/Research/python/lsst/survey_simulator/sorcha/sorcha2/sorcha/src/sorcha/ephemeris/simulation_driver.py", line 195 in update_pixel_dict
 File "/Users/mschwamb/Research/python/lsst/survey_simulator/sorcha/sorcha2/sorcha/src/sorcha/ephemeris/simulation_driver.py", line 84 in create_ephemeris
 File "/Users/mschwamb/Research/python/lsst/survey_simulator/sorcha/sorcha2/sorcha/src/sorcha/sorcha.py", line 185 in runLSSTSimulation
 File "/Users/mschwamb/Research/python/lsst/survey_simulator/sorcha/sorcha2/sorcha/src/sorcha/sorcha.py", line 491 in main
 File "/Users/mschwamb/mambaforge/envs/sorcha/bin/sorcha", line 8 in <module>
Extension modules: numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, erfa.ufunc, scipy._lib._ccallback_c, scipy.special._ufuncs_cxx, scipy.special._ufuncs, scipy.special._specfun, scipy.special._comb, scipy.linalg._fblas, scipy.linalg._flapack, scipy.linalg.cython_lapack, scipy.linalg._cythonized_array_utils, scipy.linalg._solve_toeplitz, scipy.linalg._decomp_lu_cython, scipy.linalg._matfuncs_sqrtm_triu, scipy.linalg.cython_blas, scipy.linalg._matfuncs_expm, scipy.linalg._decomp_update, scipy.sparse._sparsetools, _csparsetools, scipy.sparse._csparsetools, scipy.sparse.linalg._isolve._iterative, scipy.sparse.linalg._dsolve._superlu, scipy.sparse.linalg._eigen.arpack._arpack, scipy.sparse.csgraph._tools, scipy.sparse.csgraph._shortest_path, scipy.sparse.csgraph._traversal, scipy.sparse.csgraph._min_spanning_tree, scipy.sparse.csgraph._flow, scipy.sparse.csgraph._matching, scipy.sparse.csgraph._reordering, scipy.linalg._flinalg, scipy.special._ellip_harm_2, scipy.integrate._odepack, scipy.integrate._quadpack, scipy.integrate._vode, scipy.integrate._dop, scipy.integrate._lsoda, scipy.optimize._minpack2, scipy.optimize._group_columns, scipy._lib.messagestream, scipy.optimize._trlib._trlib, numpy.linalg.lapack_lite, scipy.optimize._lbfgsb, _moduleTNC, scipy.optimize._moduleTNC, scipy.optimize._cobyla, scipy.optimize._slsqp, scipy.optimize._minpack, scipy.optimize._lsq.givens_elimination, scipy.optimize._zeros, scipy.optimize.__nnls, scipy.optimize._highs.cython.src._highs_wrapper, scipy.optimize._highs._highs_wrapper, scipy.optimize._highs.cython.src._highs_constants, scipy.optimize._highs._highs_constants, scipy.linalg._interpolative, scipy.optimize._bglu_dense, scipy.optimize._lsap, scipy.spatial._ckdtree, scipy.spatial._qhull, scipy.spatial._voronoi, scipy.spatial._distance_wrap, scipy.spatial._hausdorff, scipy.spatial.transform._rotation, scipy.optimize._direct, astropy.time._parse_times, astropy.table._column_mixins, astropy.table._np_utils, yaml._yaml, [astropy.io](http://astropy.io/).ascii.cparser, astropy.utils.xml._iterparser, [astropy.io](http://astropy.io/).fits._utils, [astropy.io](http://astropy.io/).fits._tiled_compression._compression, [astropy.io](http://astropy.io/).votable.tablewriter, astropy.wcs._wcs, scipy.interpolate._fitpack, scipy.interpolate.dfitpack, scipy.interpolate._bspl, scipy.interpolate._ppoly, scipy.interpolate.interpnd, scipy.interpolate._rbfinterp_pythran, scipy.interpolate._rgi_cython, _brotli, astropy.stats._stats, astropy.stats._fast_sigma_clip, bottleneck.move, bottleneck.nonreduce, bottleneck.nonreduce_axis, bottleneck.reduce, astropy.timeseries.periodograms.lombscargle.implementations.cython_impl, astropy.timeseries.periodograms.bls._impl, synphot.synphot_utils, pandas._[libs.tslibs.np](http://libs.tslibs.np/)_datetime, pandas._libs.tslibs.dtypes, pandas._libs.tslibs.base, pandas._libs.tslibs.nattype, pandas._libs.tslibs.timezones, pandas._libs.tslibs.ccalendar, pandas._libs.tslibs.fields, pandas._libs.tslibs.timedeltas, pandas._libs.tslibs.tzconversion, pandas._libs.tslibs.timestamps, pandas._libs.properties, pandas._libs.tslibs.offsets, pandas._libs.tslibs.strptime, pandas._libs.tslibs.parsing, pandas._libs.tslibs.conversion, pandas._libs.tslibs.period, pandas._libs.tslibs.vectorized, pandas._libs.ops_dispatch, pandas._libs.missing, pandas._libs.hashtable, pandas._libs.algos, pandas._libs.interval, pandas._libs.lib, pandas._libs.ops, numexpr.interpreter, pandas._libs.arrays, pandas._libs.tslib, pandas._libs.sparse, pandas._libs.indexing, pandas._libs.index, pandas._libs.internals, pandas._libs.join, pandas._libs.writers, pandas._libs.window.aggregations, pandas._libs.window.indexers, pandas._libs.reshape, pandas._libs.groupby, pandas._libs.json, pandas._libs.parsers, pandas._libs.testing, matplotlib._c_internal_utils, PIL._imaging, matplotlib._path, kiwisolver._cext, matplotlib._image, healpy._healpy_sph_transform_lib, healpy._sphtools, healpy._pixelfunc, healpy._query_disc, healpy._masktools, healpy._hotspots, healpy._line_integral_convolution, numba.core.typeconv._typeconv, numba._helperlib, numba._dynfunc, numba._dispatcher, numba.core.runtime._nrt_python, [numba.np](http://numba.np/).ufunc._internal, numba.experimental.jitclass._box (total: 163)
zsh: bus error sorcha -c ./demo/sorcha_config_demo.ini -p ./demo/sspp_testset_colours.txt -o

https://github.com/matthewholman/assist/blob/273175781e995fbc7e88dd2b0b229f0e840ab740/assist/extras.py#L43

**Comment by mschwamb** [comment]
installing assist from git clone and pip installing -e gave no seg faults for my on my M2 Mac

**Comment by matthewholman** [comment]
I just now updated the version on pypi.  I don't know if this will make a difference, but you might give it a try.

**Comment by mschwamb** [comment]
Latest version of v1.1.4 works for my ARM mac. Mario has it working for his intel based mac and other machines with v1.1.4  and v1.1.4 

Closing ticket as it appears resolved
