### ISSUE TITLE
add docstrings and some comments to explain what's going on to ephemeris generation bits

### ISSUE THREAD

**Issue by mschwamb** [dirac-institute/sorcha#660]
I think it would be good to get the docstrings in to explain what's going on in the ephemeris generation functions. I don't think it will take very long but some quick description will be helpful to us in 6 months to a year.

**Comment by matthewholman** [comment]
Do you want docstrings imbedded in the code or somewhere else?

**Comment by matthewholman** [comment]
I added docstrings to create_ephemeris.  See #667
