### ISSUE TITLE
Rename detectors_corners.csv to LSSTCam_detectors_corners202310.csv

### ISSUE THREAD

**Issue by mschwamb** [dirac-institute/sorcha#678]
It would be good to keep version control on the camera footprint. detectors_corners.csv is very generic. Changing that name to  LSSTCam_detectors_corners202310.csv would be much more informative

**Comment by mschwamb** [comment]
I've missed this/got confused because  I saw /data/detectors_corners.csv 

Do we need detectors_corners.csv in  ../data? I think getting rid of that would be helpful. 

I think the one in tests and notebooks is okay because they're tests/examples. Mainly I want the default one that is the one used in running sorcha by default to have a clear name. 

I hope that helps

**Comment by drewoldag** [comment]
Cool, that makes sense. I'll remove the instance that is in `.../data` and leave the `.../tests/data/` and `.../docs/notebooks/` instances alone. Similarly, I'll leave the one that Max renamed alone. 

Thus, it sounds like the sum total of work here is to remove the superfluous file in `.../data/`. 

Does that sound correct?

**Comment by maxwest-uw** [comment]
the version of the file in `sorcha/data` already has this naming convention :)

**Comment by mschwamb** [comment]
This is what I see <img width="1332" alt="Screenshot 2023-09-29 at 8 12 27 PM" src="https://github.com/dirac-institute/sorcha/assets/753325/5c2a76b7-81aa-4588-9a14-0ae1a04e90e6">

**Comment by drewoldag** [comment]
I took a look at this, and it's a bit more involved than simply removing the "unused" detectors_corners.csv file in `data/`. 

That file is referenced in several config files in the `demo/` direcetory, and it's location mirrors the location of the `./src/sorca/modules/data` directory that is referenced by tooling such as the `makeConfigPP.py`. 

So short version of this is that this will take some time to untangle what is actually using it, and what isn't, and unfortunately, there will be more to this than simply removing the file.

**Comment by mschwamb** [comment]
All useful info. Thanks!

**Comment by mschwamb** [comment]
So this ticket really should be renamed to be remove /data/detectors_corners.csv  and update the config files. Sorcha is already configured that if no camera detectors file is provided to default to the one installed so we should clean this up.
