### ISSUE TITLE
Some typos in documentation - "auomtatically", "receivet", trailing whitespace, etc

### ISSUE THREAD

**Issue by rbanffy** [dirac-institute/sorcha#729]
Are these fixed in a branch other than main? If not, I can submit a PR from my fork.

A diff is available here: https://github.com/dirac-institute/sorcha/compare/main...rbanffy:sorcha:main

**Comment by mschwamb** [comment]
The plan was to go through in the next few weeks and fix all the typos, etc. So I haven't been worrying about typos. Happy to have a pull request to fix them if you're gone through and mode edits to fix typos

**Comment by rbanffy** [comment]
> The plan was to go through in the next few weeks and fix all the typos, etc. So I haven't been worrying about typos. Happy to have a pull request to fix them if you're gone through and mode edits to fix typos

At this stage, this is the extent of my ability to contribute. ;-)

I found the typos because I was readig the docs in order to understand how to run it.
