### ISSUE TITLE
conda-forge test error with assist

### ISSUE THREAD

**Issue by mschwamb** [dirac-institute/sorcha#746]
Our conda-forge sorcha feedstock is failing. It's complaining about an assist library variable.  
See: https://github.com/conda-forge/sorcha-feedstock/pull/10 and https://github.com/matthewholman/assist/issues/97

**Comment by mjuric** [comment]
👍. PR being developed/tested on https://github.com/conda-forge/assist-feedstock/pull/5

Assuming no surprises, new version of ASSIST should be up on conda-forge in an ~hour or so (CI looks good so far, waiting for it to finish on all platforms).

**Comment by mschwamb** [comment]
I see you're working your magic now @mjuric  on the sorcha-feedstock repo - Thanks @mjuric  and @matthewholman  for your help with this

**Comment by mschwamb** [comment]
Conda-forge pull request merged so closing
