### ISSUE TITLE
Error logging/die gracefully if the default config file does not exist or reading in the user provided camera detector file fails

### ISSUE THREAD

**Issue by mschwamb** [dirac-institute/sorcha#752]
Now that we have a don't have error handling on if reading in our default built-in installed config file fails or reading in the user provided one fails. We check the pathway exists for the user provided detector file, but no in the case we use the built-in version. 

https://github.com/dirac-institute/sorcha/blob/f7ae7ae7f429c9afe28c02557c4d31c1499e427a/src/sorcha/modules/PPFootprintFilter.py#L397C1-L405C47

**Comment by samncorn** [comment]
Just did a test, and a clear error is thrown when a path to a detector file is specified but doesn't exist, triggered by 

https://github.com/dirac-institute/sorcha/blob/6823cffe58c3a3c5aa2baebeb0b0da6f1d463e75/src/sorcha/modules/PPConfigParser.py#L477C1-L478C78

**Comment by mschwamb** [comment]
A different thing I'm referring to. What happens if someone accidentally removed "data/LSST_detector_corners_100123.csv" ?

**Comment by mschwamb** [comment]
This line https://github.com/dirac-institute/sorcha/blob/f7ae7ae7f429c9afe28c02557c4d31c1499e427a/src/sorcha/modules/PPFootprintFilter.py#L404 - what happens if "data/LSST_detector_corners_100123.csv" is deleted. I don't think we check it's there before trying to read it. It should be installed with the package, but someone could delete it.
