### ISSUE TITLE
Get this to work with RubinSim/other ephemeris calculators

### ISSUE THREAD

**Issue by astronomerritt** [dirac-institute/sorcha#76]
Essentially, _as long as the user has renamed the columns of their ephemerides input to match objectInField's_, then the code should run.

This would preferentially entail a function which would drop all/any irrelevant columns from the ephemerides input.

Renaming the columns to match would be left up to the user.

**Comment by fedorets** [comment]
In the newly created PPReadEphemerides function where functions that should use other ephemerides should be put there is now a check that these functions indeed contain the exact same column names as oif output.

**Comment by mschwamb** [comment]
There's this one https://github.com/kjnapier/spacerocks that I found that we might want to be compatible with down the line

**Comment by mschwamb** [comment]
Closing as this is already covered by #343
