### ISSUE TITLE
Check same columns are created/added when using 1 versus multiple filters 

### ISSUE THREAD

**Issue by mschwamb** [dirac-institute/sorcha#760]
Check and verify that the same H columns added [here](https://github.com/dirac-institute/sorcha/blob/b58fba39e8f893dc786e27b746d81973c4155f7a/src/sorcha/modules/PPApplyColourOffsets.py#L143
). Occur also when there's only a single filter as[ this line ](https://github.com/dirac-institute/sorcha/blob/b58fba39e8f893dc786e27b746d81973c4155f7a/src/sorcha/modules/PPCalculateApparentMagnitude.py#L56)does not need seem to set H_original. . Unit tests should verify the addition of the new columns.

**Comment by astronomerritt** [comment]
The code assumes that when only one observing filter is requested, the user has given H in that filter. Thus, H_filter and H_original would be identical. I can of course still add H_original as a column.

This raises a question though. If the user requested observations in 'g' only but supplied 'H_r' and a colour offset 'g-r', currently the code wouldn't work as expected - no offset would be applied. The code would run, but the magnitudes would be incorrect. Should something be done about that?

**Comment by mschwamb** [comment]
We should not have different columns based on different conditions of input. If you went down to one filter from multifilters, the user would be confused
