### ISSUE TITLE
Ast-Obs, 

### ISSUE THREAD

**Issue by Gerenjie** [dirac-institute/sorcha#796]
The Ast-Obs columns in the full output are light-time-corrected state vectors rather than ephemeris state vectors. We need to include the ephemeris state vectors in the output, either as a new column or replacing the Ast-Obs columns. I imagine Ast-Sun is not light-time-corrected (light delay is zero from the observer to the observer) but this should probably be confirmed.

**Comment by matthewholman** [comment]
I believe the Ast-Sun columns are also light-time-corrected.  I *think* that is what is needed to do the photometry properly.  If the light time is recorded, you can treat the vectors as ephemeris state vectors for the observation time minus the light time.

**Comment by mschwamb** [comment]
From the outputted heliocentric distance the light time can be calculated?

**Comment by mschwamb** [comment]
Sorted in discussions and we're going to update variable names.
