### ISSUE TITLE
Flexible output description

### ISSUE THREAD

**Issue by Gerenjie** [dirac-institute/sorcha#828]
In addition to  "basic" and "all", it would be nice for users to be able to define arbitrary subsets of columns as their own output format. 

output_size = ObjID,fieldRA,observedTrailedSourceMag,PhotometricSigmaTrailedSource(mag),zdot

Then we split the string we get we get from output_size on ',' (we must guarantee we have no commas in any column names or use some character we're sure we'll never use), and index the pandas dataframe on that list before outputting. I think this will be very easy to implement. 

We should check at the very start that custom outputs are subsets of the columns we expect to have and fail if they're wrong -- it would be a very frustrating workflow to make a typo here, have Sorcha run the whole way through, and then fail at the last second. 

P.S. Please don't ask what science experiment I'm doing that requires exactly ObjID,fieldRA,observedTrailedSourceMag,PhotometricSigmaTrailedSource(mag), and zdot. It's top-secret asteroid research.

**Comment by mschwamb** [comment]
Plan is that the requested columns existing will be checked at output. In documentation we will tell people who use this advanced feature that they should try this out with the demo function before going to do big Sorcha runs.
