### ISSUE TITLE
Config file is being read twice

### ISSUE THREAD

**Issue by astronomerritt** [dirac-institute/sorcha#831]
The config file is being read twice in sorcha.py: once in main() at [line 450](https://github.com/dirac-institute/sorcha/blob/5d606dabe9269b923c37209f6ecf45a24053754d/src/sorcha/sorcha.py#L450), and then again in runLSSTprocessing() at [line 105](https://github.com/dirac-institute/sorcha/blob/5d606dabe9269b923c37209f6ecf45a24053754d/src/sorcha/sorcha.py#L105).

Unless there's a reason why this is, one of these should be deleted.

My suggestion is to delete the instance in runLSSTprocessing() as:

- it makes more sense to parse the configuration file before we start processing
- tests will break if we do it the other way around
- I already checked and commenting out this line does nothing: all tests run

**Comment by mschwamb** [comment]
The config file has to be read in at main as there are config file variables that are needed by ephemeris generation
