### ISSUE TITLE
Ast-Sun light-time correction

### ISSUE THREAD

**Issue by Gerenjie** [dirac-institute/sorcha#841]
**Describe the issue and the steps to reproduce the behavior**
Ast-Sun columns (Ast-Sun(J2000x)(km), etc) are light-time-corrected positions rather than positions at FieldMJD_TAI/JD_TDB. 

Recommended fix:
in simulation_driver.py, after line 197, overwrite out_tuple's (x,y,z,vx,vy,vz) indices with something from sim.

[197] out_tuple = calculate_rates_and_geometry(pointing, ephem_geom_params)
[198] out_tuple[something] = sim[something]
[199] in_memory_csv.writerow(out_tuple)

Not sure if this breaks things, though. 

Alternative fix: document that these columns are light-time-corrected.

**Comment by mschwamb** [comment]
We're going to update the variable names/column headings
