### ISSUE TITLE
Update apparent magnitude validation notebook 

### ISSUE THREAD

**Issue by bernardinelli** [dirac-institute/sorcha#845]
It seems that JPL's apparent magnitude calculation is a bit fancier than the standard HG/HG12/HG1G2 model, and produces 20-40mmag offsets between what is being shown in the current version of the notebook

So we'll show that is a JPL and not a sorcha thing by testing against Pedro's independent implementation of these phase curves

**Comment by mschwamb** [comment]
@bernardinelli  would you be able to take a stab at adding to the notebook?

**Comment by bernardinelli** [comment]
This is already implemented inside `demo_ApparentMagnitudeValidation.ipynb` - it was pushed (by mistake by me) in my fast mover monster PR!
