### ISSUE TITLE
Not checking that ephemeris file already exists when running more than once

### ISSUE THREAD

**Issue by astjoephysics** [dirac-institute/sorcha#866]
Using the -ew flag, it seems that the main branch is writing the exact same ephemeris twice when it saves. I have looked at the main branch vs the fast movers branch, and the fast mover branch output is e.g. len=17.5k whereas the main branch is len=35k. The main branch values are the exact same as the fast mover branch values from lines 0-17.5k, after which the repeat again.

**Comment by astjoephysics** [comment]
EDIT: the memory mapped CSV output is fine, but it's not checking that the same file exists or not if you run it more than once, so it is currently appending to an existing output file if it already exists.

**Comment by bernardinelli** [comment]
Which version of the main branch are you using? (the latest one should incorporate the fast mover stuff). 
It's totally possible I removed something when implementing the new ephemeris stuff....

**Comment by mschwamb** [comment]
He was using the latest version in my office when he showed me.

**Comment by mschwamb** [comment]
I think it's actually intended behavior. More of a feature... The memory mapped csv appends by default, which I think is what you want because for each chunk of objects read in you'll want to keep adding to the file. So  I think earlier on in the argument parser it should but does not check that the ephemeris file already exists

**Comment by mschwamb** [comment]
Found the issue - the ArgParser assumes that we're providing the full filename when it's really a stem and we actually output it to the output folder.  So it's checking for a file exists, but it's actually checking for the wrong file https://github.com/dirac-institute/sorcha/blob/b9ce82b39006d37c588e4a24186518c74a8a17cd/src/sorcha/modules/PPCommandLineParser.py#L79C1-L80C86
