### ISSUE TITLE
Add heliocentric distance to basic output

### ISSUE THREAD

**Issue by mschwamb** [dirac-institute/sorcha#894]
Heliocentric distance will be a useful value to include for the default basic output

**Comment by astjoephysics** [comment]
Heliocentric distance is only ever calculated explicitly in PPCalculateApparentMagnitudeInFilter (which does have a reference for Ast-Sun in the observations dataframe, so potentially this was meant to be included in the first place?). Do we want to put another calculation in PPOutput for basic (and full?) outputs?

**Comment by mschwamb** [comment]
@astronomerritt has a list of things to do to the updating the Sorcha output so we'll lump that into the one PR
