### ISSUE TITLE
hidden config variable to turn vignetting off

### ISSUE THREAD

**Issue by mschwamb** [dirac-institute/sorcha#901]
hidden config variable to turn vignetting off

**Comment by astronomerritt** [comment]
What should happen if vignetting is turned off? Currently PPVignetting creates the "fiveSigmaDepth_mag" column in the dataframe, which is then used to calculate uncertainties and detection probability/fading function. This column is also in the basic output.  

If vignetting is off, should "fieldFiveSigmaDepth_mag" from the pointing database be copied into this column instead?

**Comment by mschwamb** [comment]
yep
