### ISSUE TITLE
Add a chunk counter and output that value to the log so the user knows that chunk the code is on

### ISSUE THREAD

**Issue by mschwamb** [dirac-institute/sorcha#907]
Add a chunk counter and output that value to the log so the user knows that chunk the code is on

**Comment by astronomerritt** [comment]
As far as we can tell something like this already exists in the code (line 177 of sorcha.py). Is something more needed?

**Comment by mschwamb** [comment]
You have to do some mathematics to figure out if you're on chunk 3 or 5. So I think it's useful to know what set of orbits for debgugging on chunk x of 1000 would be helpful for checking progress.
