### ISSUE TITLE
Add docstrings for pixel_dict.py and simulation_geometry.py  & question about doc string in simulation_drive.py

### ISSUE THREAD

**Issue by mschwamb** [dirac-institute/sorcha#918]
docstrings are missing from some functions in pixel_dict.py and simulation_geometry.py

Also for docstrings for  get_residual_vectors(v1) in simulation_drive.py  - what is A and what is D?

**Comment by bernardinelli** [comment]
I tried to improve the documentation a bit on A and D, but I think it's still bad. The idea here is that A = (- sin (RA), cos(RA), 0) and D = (- sin(dec) cos (RA), - sin(dec) sin(RA), cos(dec)), which facilitates vector algebra
