### ISSUE TITLE
Refactor PPConfigParser

### ISSUE THREAD

**Issue by astronomerritt** [dirac-institute/sorcha#921]
It's nearly 1000 lines long and it was barely fit for purpose back when we had half the config flags we do now.  We're currently in a position where adding or editing new config file keys is an absolute nightmare.

Ideally this would be a dataclass like sorchaArguments.py.

(This can be a v2.0 thing. Although I wonder if the JOSS reviewers might say something.)

**Comment by mschwamb** [comment]
Already issue #537
