### ISSUE TITLE
Change behaviour of Linked column in miniDifi

### ISSUE THREAD

**Issue by astronomerritt** [dirac-institute/sorcha#952]
The Linked column in miniDifi should mark any observations of an object that take place before the date of linking/discovery as False.

**Comment by mschwamb** [comment]
I believe we've changed this in a different way is that right @astronomerritt  and @bernardinelli ?

**Comment by astronomerritt** [comment]
It hasn't been changed as far as I know. It's a simple True/False per object stating whether the object was linked or not. Did you want something different?

**Comment by mschwamb** [comment]
I thought you were changing the name of the column so it was clearer instead because this ticket is not feasible given the discussion yesterday.

**Comment by astronomerritt** [comment]
We were going to change the name of the column back when we were still thinking of changing the column behaviour. 

I can change the column name anyway. "object_linked" or something similar might be clearer.

**Comment by mschwamb** [comment]
Yeah that might be helpful
