### ISSUE TITLE
'float' object has no attribute 'sqrt'

### ISSUE THREAD

**Issue by mschwamb** [dirac-institute/sorcha#973]
got this error on hpc for one of my runs

AttributeError: 'float' object has no attribute 'sqrt'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mschwamb/.conda/envs/sorcha/bin/sorcha", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mschwamb/sorcha/src/sorcha/sorcha.py", line 541, in main
    runLSSTSimulation(args, configs)
  File "/home/mschwamb/sorcha/src/sorcha/sorcha.py", line 249, in runLSSTSimulation
    observations = PPAddUncertainties.addUncertainties(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mschwamb/sorcha/src/sorcha/modules/PPAddUncertainties.py", line 102, in addUncertainties
    detDF["astrometricSigma_deg"], detDF["trailedSourceMagSigma"], detDF["SNR"] = uncertainties(
                                                                                  ^^^^^^^^^^^^^^
  File "/home/mschwamb/sorcha/src/sorcha/modules/PPAddUncertainties.py", line 186, in uncertainties
    astrSig, SNR, _ = calcAstrometricUncertainty(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mschwamb/sorcha/src/sorcha/modules/PPAddUncertainties.py", line 266, in calcAstrometricUncertainty
    SNR = 1.0 / np.sqrt((0.04 - rgamma) * xval + rgamma * xval * xval)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mschwamb/.conda/envs/sorcha/lib/python3.11/site-packages/pandas/core/generic.py", line 2171, in __array_ufunc__
    return arraylike.array_ufunc(self, ufunc, method, *inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mschwamb/.conda/envs/sorcha/lib/python3.11/site-packages/pandas/core/arraylike.py", line 399, in array_ufunc
    result = getattr(ufunc, method)(*inputs, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: loop of ufunc does not support argument 0 of type float which has no callable sqrt method

Inputs:

[PLTI_orbits_Fiducial_Model_H-5.00_a195.00.csv](https://github.com/user-attachments/files/15924568/PLTI_orbits_Fiducial_Model_H-5.00_a195.00.csv)
[PLTI_physical_parameters_Fiducial_Model_H-5.00_a195.00.csv](https://github.com/user-attachments/files/15924569/PLTI_physical_parameters_Fiducial_Model_H-5.00_a195.00.csv)

I was running without phase curves and u and y.  

import numpy as np; print("np", np.__version__)
np 1.26.4

**Comment by astronomerritt** [comment]
Do you know what chunk of objects this was happening for?

**Comment by mschwamb** [comment]
I also seem to have multiple log files at the same time is this directory. So I'm suspicious it's user error but I don't see how that would cause this error

**Comment by mschwamb** [comment]
2 chunk of 5000

**Comment by astronomerritt** [comment]
Cool, I can run locally and try to replicate.

**Comment by mschwamb** [comment]
I'm running with baseline 3.4 for the survey sim

**Comment by astronomerritt** [comment]
My Kelvin run did not produce this error for those input files and I can't reproduce it locally either. 

Both using numpy 1.26.4, no phase function, r,g,i,z filters only.

However, I _can_ replicate this error in a notebook as follows:

```
import numpy as np
from sorcha.modules.PPAddUncertainties import calcAstrometricUncertainty

mag = np.array([4., 5.], dtype=object)
m5 = np.array([5., 6.])

calcAstrometricUncertainty(mag, m5)
```

This reproduces the error you posted above.

I'd guess that something in your run is causing the `trailedSourceMagTrue` or the `fiveSigmaDepth_mag` columns in the dataframe to be typed as something that isn't floats. Pandas infers typing for columns and nothing in the readers code sets the types explicitly on read-in, so it may have inferred incorrectly.

What Pandas version are you using?

**Comment by mschwamb** [comment]
Not sure, but if latest versions this is not happening then we should just leave this
