### ISSUE TITLE
Command line argument naming should follow UNIX conventions

### ISSUE THREAD

**Issue by mjuric** [dirac-institute/sorcha#978]
Unix programs these days typically follow the [GNU conventions](https://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html) for command line arguments. We deviate from them in two ways:

* Have short arguments with more than one character (e.g. `-cp` in `sorcha run`). This is ambiguous with shortening `-c -p` as `-cp` (see the second bullet [here](https://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html)), and makes `argparse` disable this feature entirely.
* Have long arguments with underscores (`_`). This goes against GNU conventions (quote: "Long options consist of -- followed by a name made of alphanumeric characters and dashes."), but more importantly it makes our code feel a bit unnatural (very Java-ish). E.g., run `git add --help` or `ls --help` (on linux) to see the difference.

I propose we fix this now, before the cmdline API is frozen for v1.0 -- it will be very hard (impossible) to change later. The fix is easy (I'm volunteering to do it).

<img width="940" alt="image" src="https://github.com/user-attachments/assets/88becc29-08c1-4e8a-b899-59e6f2cff81b">

**Comment by mjuric** [comment]
Current WIP prototype (early comments welcome):
<img width="1264" alt="image" src="https://github.com/user-attachments/assets/6927bd65-a295-45cc-ad74-d0e9904151ab">

**Comment by mschwamb** [comment]
command line argument --help needs to show what parameters are required and which are optional

**Comment by mschwamb** [comment]
@mjuric  since we have a full draft of the paper and we have a list of variable names - can you get to this, since you're the one who wanted this?

**Comment by mjuric** [comment]
By when would you need it (assessing what's possible w. my schedule these days...)?

**Comment by mschwamb** [comment]
end of November - for submission of the paper

**Comment by mjuric** [comment]
See the PR #1064 -- this implements the minimal changes requested (plus I changed `--orbit` to `--orbits`).

Notes:
* codecov is complaining for unknown reasons; I'll leave you to figure it out (I failed :( ).
* Having a `--verbose` option which defaults to `true` and has to be turned off as `--verbose=false` is double-plus-super-wrong, IMHO. Super confusing. Can't think of any other piece of code that does it. I'm getting a rash just thinking about how wrong this is. Also, `--verbose` is generally understood to increase console verbosity -- for log file control, something like `--log-level` would feel more natural.
* still think our general cmdline ergonomics is a mess. Having required options (i.e. `--foo xxx`) feels unnatural. We have too few defaults (ergo too much writing). The log file handling (two files, with randomly generated names) doesn't lend itself to simple scripting, etc. Registering my general sadness (re-trigged by having to look at this code again) that we didn't fix this when we had a chance (now).

**Comment by mschwamb** [comment]
Thanks

The verbose was eventually going to get changed, it's that the verbose logging was helpful when we were in code development so easier to force it to be on while we were in that state. Turning it off makes the log files pithier so we're at that stage where we can do the correct behavior.  Blame this one on me. 

We had a discussion of config file and we use the different names to run through and check that all the runs completed. The user can specify the stem of the filename so removing them can be scripted.

**Comment by mschwamb** [comment]
If you want to change verbose to log-level go for it
